# Generated by Django 5.0.4 on 2024-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="frequency",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="frequency_of_memory",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="frequency",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ram",
            name="frequency",
            field=models.IntegerField(null=True),
        ),
    ]
